# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('weekly_tasks.json', '.'),
        ('wwbs.ico', '.'),
        ('assets/run-notice', 'assets/run-notice'),
        ('pet-assets/pink-lace-chibi/frames', 'pet-assets/pink-lace-chibi/frames'),
        ('pet-assets/aemeath-chibi/frames-sharp', 'pet-assets/aemeath-chibi/frames-sharp'),
        ('pet-assets/jingran-chibi/frames', 'pet-assets/jingran-chibi/frames'),
        ('pet-assets/jingran-chibi/pet.json', 'pet-assets/jingran-chibi'),
        ('pet-assets/jingran-chibi/spritesheet.webp', 'pet-assets/jingran-chibi'),
        ('optional-themes/daniya-theme.wwbstheme', 'optional-themes'),
        ('optional-themes/aemeath-theme.wwbstheme', 'optional-themes'),
        ('optional-themes/jingran-theme.wwbstheme', 'optional-themes'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'torch',
        'matplotlib',
        'pandas',
        'pyarrow',
        'sklearn',
        'sympy',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'psutil',
        'jinja2',
        'dateutil',
        'pytz',
        'cryptography',
        'urllib3',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='wwbs',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['wwbs.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='wwbs',
)
