"""Historical seeds are literal fixtures, never regenerated by the current codec."""
import json
from pathlib import Path
import unittest
from unittest.mock import patch

import combat_rotation
from combat_seed import decode_seed, import_seed


FIXTURES = json.loads((Path(__file__).parent / 'fixtures' / 'seed-compatibility.json').read_text(encoding='utf-8'))


def snapshot(preset):
    return {key: preset[key] for key in ('name', 'slot_order', 'slot_times')} | {
        'modules': [{key: m[key] for key in ('kind', 'slot', 'value', 'interval')}
                    for m in preset['modules']]}


class SeedCompatibilityTests(unittest.TestCase):
    def test_all_published_seed_generations_restore_original_content(self):
        for fixture in FIXTURES:
            with self.subTest(format=fixture['label']):
                self.assertEqual(snapshot(decode_seed(fixture['seed'])), fixture['expected'])

    def test_changing_new_axis_defaults_cannot_change_old_seeds(self):
        with patch.dict(combat_rotation.DEFAULT_VALUES, {
                'skill': (1, 99), 'ultimate': (1, 110), 'idle_attack': (35, 0), 'wait': (20, 0)}):
            for fixture in FIXTURES:
                with self.subTest(format=fixture['label']):
                    self.assertEqual(snapshot(decode_seed(fixture['seed'])), fixture['expected'])

    def test_historical_seed_import_keeps_existing_presets_and_modes(self):
        store = combat_rotation.validate_store(combat_rotation.default_store())
        old_presets, old_modes = store['presets'], store['modes']
        for fixture in FIXTURES:
            with self.subTest(format=fixture['label']):
                imported, identity = import_seed(store, fixture['seed'])
                self.assertEqual(imported['presets'][:-1], old_presets)
                self.assertEqual(imported['modes'], old_modes)
                preset = next(p for p in imported['presets'] if p['id'] == identity)
                checked = snapshot(preset)
                checked['name'] = fixture['expected']['name']
                self.assertEqual(checked, fixture['expected'])


if __name__ == '__main__':
    unittest.main()
